### ISSUE TITLE
Improve glucoseVectorToTimetable function to handle optional input parameters

### ISSUE THREAD

**Issue by NunzioCamer** [gcappon/agata#21]
**Is your feature request related to a problem? Please describe.**
In the current function, inputs must follow a pre-established order.

**Describe the solution you'd like**
Use an input parser to add optional parameters like sample time and start time.

**Comment by gcappon** [comment]
Remember that sampleTime is not optional. The only optional parameter is startTine

**Comment by gcappon** [comment]
Not necessary anymore.
