### ISSUE TITLE
Add a function to compute ISO for different ranges

### ISSUE THREAD

**Issue by NunzioCamer** [gcappon/agata#27]
**Description**
Percent of data matching the International Organization for Standardization (ISO) 15197:2013.
Ex. ISO 15-15%: Percentage of sensor data within ±15% of reference value for glucose concentrations ≥100 mg/dl, and within ±15 mg/dl of reference value for glucose concentrations <100 mg/dl.

**Comment by gcappon** [comment]
Closing this issue since it would need ysi data
